/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:controlWin:658228:
  appc.background(230);
} //_CODE_:controlWin:658228:

public void btnApply_click(GButton source, GEvent event) { //_CODE_:btnApply:462487:
  onUpdateSettings.fire();
} //_CODE_:btnApply:462487:

public void btnPlot_click(GButton source, GEvent event) { //_CODE_:btnPlot:918226:
} //_CODE_:btnPlot:918226:

public void btnClear_click(GButton source, GEvent event) { //_CODE_:btnClear:436043:
  onClear.fire();
} //_CODE_:btnClear:436043:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  controlWin = GWindow.getWindow(this, "Control Window", 0, 0, 600, 400, JAVA2D);
  controlWin.noLoop();
  controlWin.setActionOnClose(G4P.KEEP_OPEN);
  controlWin.addDrawHandler(this, "win_draw1");
  xAxisSlider = new GCustomSlider(controlWin, 16, 40, 152, 53, "grey_blue");
  xAxisSlider.setShowValue(true);
  xAxisSlider.setLimits(1, 1, 10);
  xAxisSlider.setShowTicks(true);
  xAxisSlider.setNumberFormat(G4P.INTEGER, 0);
  xAxisSlider.setOpaque(false);
  label1 = new GLabel(controlWin, 16, 16, 80, 20);
  label1.setTextAlign(GAlign.LEFT, GAlign.BOTTOM);
  label1.setText("X-Axis Scale");
  label1.setOpaque(false);
  btnApply = new GButton(controlWin, 264, 102, 80, 30);
  btnApply.setText("Apply");
  btnApply.addEventHandler(this, "btnApply_click");
  label2 = new GLabel(controlWin, 192, 16, 80, 20);
  label2.setText("Y-Axis Scale");
  label2.setOpaque(false);
  yAxisSlider = new GCustomSlider(controlWin, 192, 40, 152, 56, "grey_blue");
  yAxisSlider.setShowValue(true);
  yAxisSlider.setLimits(1, 1, 10);
  yAxisSlider.setShowTicks(true);
  yAxisSlider.setNumberFormat(G4P.INTEGER, 0);
  yAxisSlider.setOpaque(false);
  plotPointTxt = new GTextField(controlWin, 18, 120, 150, 30, G4P.SCROLLBARS_NONE);
  plotPointTxt.setOpaque(true);
  label3 = new GLabel(controlWin, 18, 102, 80, 20);
  label3.setText("Plot Point");
  label3.setOpaque(false);
  btnPlot = new GButton(controlWin, 120, 156, 48, 30);
  btnPlot.setText("Plot");
  btnPlot.addEventHandler(this, "btnPlot_click");
  btnClear = new GButton(controlWin, 260, 185, 80, 30);
  btnClear.setText("Clear");
  btnClear.setLocalColorScheme(GCScheme.RED_SCHEME);
  btnClear.addEventHandler(this, "btnClear_click");
  controlWin.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow controlWin;
GCustomSlider xAxisSlider; 
GLabel label1; 
GButton btnApply; 
GLabel label2; 
GCustomSlider yAxisSlider; 
GTextField plotPointTxt; 
GLabel label3; 
GButton btnPlot; 
GButton btnClear; 
